### ISSUE TITLE
请问下，训练时出现OutOfRangeError是什么情况呢？

### ISSUE THREAD

**Issue by AndyZCJ** [YangZeyu95/unofficial-implement-of-openpose#12]
训练的时候出了个叫OutOfRangeError的错误，报错信息如下2019-01-29 15:02:54,044] [pose_dataset] [ERROR] err type2, err=Cannot feed value of shape (10, 184, 184, 19) for Tensor 'inputs/Placeholder_1:0', which has shape '(10, 46, 46, 19)', placeholders=[<tf.Tensor 'inputs/Placeholder:0' shape=(10, 368, 368, 3) dtype=float32>, <tf.Tensor 'inputs/Placeholder_1:0' shape=(10, 46, 46, 19) dtype=float32>, <tf.Tensor 'inputs/Placeholder_2:0' shape=(10, 46, 46, 38) dtype=float32>]
[2019-01-29 15:02:54,045] [pose_dataset] [ERROR] Exception in Thread-1:Cannot feed value of shape (10, 184, 184, 19) for Tensor 'inputs/Placeholder_1:0', which has shape '(10, 46, 46, 19)'
Traceback (most recent call last):
  File "F:\pose\unofficial-implement-of-openpose-master\pose_dataset.py", line 442, in run
    self.op.run(feed_dict=feed)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2241, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 4986, in _run_using_default_session
    session.run(operation, feed_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1076, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (10, 184, 184, 19) for Tensor 'inputs/Placeholder_1:0', which has shape '(10, 46, 46, 19)'
[2019-01-29 15:02:55,525] [pose_dataset] [INFO] Thread-1 Exited.

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 198, in <module>
    train()
  File "train.py", line 164, in train
    total_loss, _, gs_num = sess.run([loss, train, global_step])
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue)]]

Caused by op 'fifo_queue_Dequeue', defined at:
  File "train.py", line 198, in <module>
    train()
  File "train.py", line 82, in train
    q_inp, q_heat, q_vect = enqueuer.dequeue()
  File "F:\pose\unofficial-implement-of-openpose-master\pose_dataset.py", line 464, in dequeue
    return self.queue.dequeue()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 433, in dequeue
    self._queue_ref, self._dtypes, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4096, in queue_dequeue_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue)]]

**Comment by YangZeyu95** [comment]
应该是因为最前面 输入数据维度和placholder 不一致导致的，已经收到几个在Windows上运行有相同的情况。应该是因为scale设置没起作用，试下把pose_augment.py中的line263-264中的_scale改成8试试。

**Comment by AndyZCJ** [comment]
谢谢您的回复！刚刚把scale改成了8就能正常训练了，非常感谢！




------------------ 原始邮件 ------------------
发件人: "YangZeyu"<notifications@github.com>;
发送时间: 2019年1月30日(星期三) 晚上6:38
收件人: "YangZeyu95/unofficial-implement-of-openpose"<unofficial-implement-of-openpose@noreply.github.com>;
抄送: "周楚晋"<2290151272@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [YangZeyu95/unofficial-implement-of-openpose] 请问下，训练时出现OutOfRangeError是什么情况呢？ (#12)




应该是因为最前面 输入数据维度和placholder 不一致导致的，已经收到几个在Windows上运行有相同的情况。应该是因为scale设置没起作用，试下把pose_augment.py中的line263-264中的_scale改成8试试。

**Comment by AndyZCJ** [comment]
> 应该是因为最前面 输入数据维度和placholder 不一致导致的，已经收到几个在Windows上运行有相同的情况。应该是因为scale设置没起作用，试下把pose_augment.py中的line263-264中的_scale改成8试试。

还有个小问题，昨天晚上开始训练指导今天，我发现它训练了至少三遍，进度条从0到100然后又归0，这是为什么呢？

**Comment by YangZeyu95** [comment]
这个没问题 进度是数据集上每一轮的进度
