### ISSUE TITLE
train

### ISSUE THREAD

**Issue by gouyinchao** [YangZeyu95/unofficial-implement-of-openpose#21]
Instructions for updating:
Use standard file APIs to check for files with this prefix.
[2019-04-13 18:25:02,982] [train] [INFO] restoring from checkpoint...
[2019-04-13 18:25:02,982] [train] [INFO] start training...
  0%|                                                  | 0/1848 [00:00<?, ?it/s]

why the process stop 0% for a long time,is it wrong?or it maybe just running?Can you help me please?

**Comment by YangZeyu95** [comment]
It seems that you are finetuning on your dataset. I have had an almost same issue when finetuning and it's a problem of data loader. Make sure get_data() function in  CocoPose class works well.

**Comment by soveidadelgarmi** [comment]
Hi, I run train.py with coco dataset and I didn't have any problems. now I want to finetune it on my own dataset. but I receive this error...., I don't know what should I do exactly to solve it? can someone help me?

errore is:
[2019-07-14 07:50:50,943] [train] [INFO] start training...
I0714 07:50:50.943787 140334568265600 <ipython-input-3-ab88d0c70200>:181] start training...
  0%|          | 0/21 [00:00<?, ?it/s][2019-07-14 07:50:51,013] [pose_dataset] [ERROR] err type2, err=Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)', placeholders=[<tf.Tensor 'inputs/Placeholder:0' shape=(5, 368, 368, 3) dtype=float32>, <tf.Tensor 'inputs/Placeholder_1:0' shape=(5, 46, 46, 11) dtype=float32>, <tf.Tensor 'inputs/Placeholder_2:0' shape=(5, 46, 46, 22) dtype=float32>]
E0714 07:50:51.013219 140329005074176 pose_dataset.py:485] err type2, err=Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)', placeholders=[<tf.Tensor 'inputs/Placeholder:0' shape=(5, 368, 368, 3) dtype=float32>, <tf.Tensor 'inputs/Placeholder_1:0' shape=(5, 46, 46, 11) dtype=float32>, <tf.Tensor 'inputs/Placeholder_2:0' shape=(5, 46, 46, 22) dtype=float32>]
[2019-07-14 07:50:51,015] [pose_dataset] [ERROR] Exception in Thread-5:Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)'
Traceback (most recent call last):
  File "/content/drive/My Drive/Mythesiscode/pose_dataset.py", line 479, in run
    self.op.run(feed_dict=feed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2679, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 5614, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)'
E0714 07:50:51.015784 140329005074176 pose_dataset.py:489] Exception in Thread-5:Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)'
Traceback (most recent call last):
  File "/content/drive/My Drive/Mythesiscode/pose_dataset.py", line 479, in run
    self.op.run(feed_dict=feed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2679, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 5614, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)'


OutOfRangeError: 2 root error(s) found.
  (0) Out of range: FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[node fifo_queue_Dequeue (defined at /content/drive/My Drive/Mythesiscode/pose_dataset.py:501) ]]
  (1) Out of range: FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[node fifo_queue_Dequeue (defined at /content/drive/My Drive/Mythesiscode/pose_dataset.py:501) ]]
	 [[fifo_queue_Dequeue/_75]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node fifo_queue_Dequeue:
 fifo_queue (defined at /content/drive/My Drive/Mythesiscode/pose_dataset.py:440)

Input Source operations connected to node fifo_queue_Dequeue:
 fifo_queue (defined at /content/drive/My Drive/Mythesiscode/pose_dataset.py:440)

Original stack trace for 'fifo_queue_Dequeue':
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-07e8d33e3ad1>", line 2, in <module>
    train()
  File "<ipython-input-3-ab88d0c70200>", line 78, in train
    q_inp, q_heat, q_vect = enqueuer.dequeue()
  File "/content/drive/My Drive/Mythesiscode/pose_dataset.py", line 501, in dequeue
    return self.queue.dequeue()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 445, in dequeue
    self._queue_ref, self._dtypes, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4140, in queue_dequeue_v2
    timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by ccl-private** [comment]
@soveidadelgarmi checkout your feed images finally become the shape of (368, 368, 3).

**Comment by aniketzz** [comment]
I am also having the same issue. Could any one please elaborate the solution

**Comment by aniketzz** [comment]
I am currently getting this error :

OutOfRangeError (see above for traceback): FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[{{node fifo_queue_Dequeue}} = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue)]]

**Comment by aniketzz** [comment]
this is the error that I am getting. 

Traceback (most recent call last):
  File "train.py", line 206, in <module>
    train()
  File "train.py", line 172, in train
    total_loss, a, gs_num = sess.run([loss, train, global_step])
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1286, in _do_run
    run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[{{node fifo_queue_Dequeue}} = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue)]]

**Comment by cohogain** [comment]
> Hi, I run train.py with coco dataset and I didn't have any problems. now I want to finetune it on my own dataset. but I receive this error...., I don't know what should I do exactly to solve it? can someone help me?
> 
> errore is:
> [2019-07-14 07:50:50,943] [train] [INFO] start training...
> I0714 07:50:50.943787 140334568265600 :181] start training...
> 0%| | 0/21 [00:00<?, ?it/s][2019-07-14 07:50:51,013] [pose_dataset] [ERROR] err type2, err=Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)', placeholders=[<tf.Tensor 'inputs/Placeholder:0' shape=(5, 368, 368, 3) dtype=float32>, <tf.Tensor 'inputs/Placeholder_1:0' shape=(5, 46, 46, 11) dtype=float32>, <tf.Tensor 'inputs/Placeholder_2:0' shape=(5, 46, 46, 22) dtype=float32>]
> E0714 07:50:51.013219 140329005074176 pose_dataset.py:485] err type2, err=Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)', placeholders=[<tf.Tensor 'inputs/Placeholder:0' shape=(5, 368, 368, 3) dtype=float32>, <tf.Tensor 'inputs/Placeholder_1:0' shape=(5, 46, 46, 11) dtype=float32>, <tf.Tensor 'inputs/Placeholder_2:0' shape=(5, 46, 46, 22) dtype=float32>]
> [2019-07-14 07:50:51,015] [pose_dataset] [ERROR] Exception in Thread-5:Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)'
> Traceback (most recent call last):
> File "/content/drive/My Drive/Mythesiscode/pose_dataset.py", line 479, in run
> self.op.run(feed_dict=feed)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2679, in run
> _run_using_default_session(self, feed_dict, self.graph, session)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 5614, in _run_using_default_session
> session.run(operation, feed_dict)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
> run_metadata_ptr)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1149, in _run
> str(subfeed_t.get_shape())))
> ValueError: Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)'
> E0714 07:50:51.015784 140329005074176 pose_dataset.py:489] Exception in Thread-5:Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)'
> Traceback (most recent call last):
> File "/content/drive/My Drive/Mythesiscode/pose_dataset.py", line 479, in run
> self.op.run(feed_dict=feed)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2679, in run
> _run_using_default_session(self, feed_dict, self.graph, session)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 5614, in _run_using_default_session
> session.run(operation, feed_dict)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
> run_metadata_ptr)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1149, in _run
> str(subfeed_t.get_shape())))
> ValueError: Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)'
> 
> OutOfRangeError: 2 root error(s) found.
> (0) Out of range: FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
> [[node fifo_queue_Dequeue (defined at /content/drive/My Drive/Mythesiscode/pose_dataset.py:501) ]]
> (1) Out of range: FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
> [[node fifo_queue_Dequeue (defined at /content/drive/My Drive/Mythesiscode/pose_dataset.py:501) ]]
> [[fifo_queue_Dequeue/_75]]
> 0 successful operations.
> 0 derived errors ignored.
> 
> Errors may have originated from an input operation.
> Input Source operations connected to node fifo_queue_Dequeue:
> fifo_queue (defined at /content/drive/My Drive/Mythesiscode/pose_dataset.py:440)
> 
> Input Source operations connected to node fifo_queue_Dequeue:
> fifo_queue (defined at /content/drive/My Drive/Mythesiscode/pose_dataset.py:440)
> 
> Original stack trace for 'fifo_queue_Dequeue':
> File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py", line 16, in
> app.launch_new_instance()
> File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 658, in launch_instance
> app.start()
> File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py", line 477, in start
> ioloop.IOLoop.instance().start()
> File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 888, in start
> handler_func(fd_obj, events)
> File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
> return fn(*args, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
> self._handle_recv()
> File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
> self._run_callback(callback, msg)
> File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
> callback(*args, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
> return fn(*args, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
> return self.dispatch_shell(stream, msg)
> File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
> handler(stream, idents, msg)
> File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
> user_expressions, allow_stdin)
> File "/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
> res = shell.run_cell(code, store_history=store_history, silent=silent)
> File "/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
> return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
> interactivity=interactivity, compiler=compiler, result=result)
> File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
> if self.run_code(code, result):
> File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
> exec(code_obj, self.user_global_ns, self.user_ns)
> File "", line 2, in
> train()
> File "", line 78, in train
> q_inp, q_heat, q_vect = enqueuer.dequeue()
> File "/content/drive/My Drive/Mythesiscode/pose_dataset.py", line 501, in dequeue
> return self.queue.dequeue()
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 445, in dequeue
> self._queue_ref, self._dtypes, name=name)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4140, in queue_dequeue_v2
> timeout_ms=timeout_ms, name=name)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
> op_def=op_def)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
> return func(*args, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
> op_def=op_def)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2005, in **init**
> self._traceback = tf_stack.extract_stack()

I am experiencing the exact same error when fine-tuning with my own data set. Did you manage to resolve this issue? It would be a great help, thanks.

**Comment by YangZeyu95** [comment]
Hi,

It seems you put heatmaps into the input placeholder?
