### ISSUE TITLE
使用COCO数据集训练时MEMORYERROR

### ISSUE THREAD

**Issue by jingshaoli** [YangZeyu95/unofficial-implement-of-openpose#30]
(base) D:\job\openposetf\unofficial-implement-of-openpose-master>python train.py
[2019-05-30 22:16:52,016] [train] [INFO] Namespace(annot_path='D:/job/openposetf/checkpoints/COCO/annotations/', backbone_net_ckpt_path='D:/job/openposetf/checkpoints/vgg/vgg_19.ckpt', batch_size=10, checkpoint_path='D:/job/openposetf/checkpoints/train/', continue_training=False, hm_channels=19, img_path='D:/job/openposetf/checkpoints/COCO/images/', input_height=368, input_width=368, loss_func='l2', max_echos=5, paf_channels=38, save_checkpoint_frequency=1000, save_summary_frequency=100, stage_num=6, train_vgg=True, use_bn=False)
[2019-05-30 22:16:52,018] [train] [INFO] checkpoint_path: D:/job/openposetf/checkpoints/train/2019-5-30-22-16-52
[2019-05-30 22:16:52,021] [train] [INFO] initializing data loader...
[2019-05-30 22:16:52,022] [pose_dataset] [INFO] dataflow img_path=D:/job/openposetf/checkpoints/COCO/images/
loading annotations into memory...
Done (t=10.02s)
creating index...
index created!
[2019-05-30 22:17:02,246] [pose_dataset] [INFO] D:/job/openposetf/checkpoints/COCO/annotations/ dataset 118287
[0530 22:17:02 @parallel.py:184] WRN MultiProcessPrefetchData does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
[0530 22:17:02 @parallel.py:194] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    train()
  File "train.py", line 78, in train
    df = get_dataflow_batch(args.annot_path, True, args.batch_size, img_path=args.img_path)
  File "D:\job\openposetf\unofficial-implement-of-openpose-master\pose_dataset.py", line 388, in get_dataflow_batch
    ds = get_dataflow(path, is_train, img_path=img_path)
  File "D:\job\openposetf\unofficial-implement-of-openpose-master\pose_dataset.py", line 367, in get_dataflow
    ds = PrefetchData(ds, 1000, multiprocessing.cpu_count()-1)
  File "D:\anaconda\lib\site-packages\tensorpack\dataflow\parallel.py", line 201, in __init__
    start_proc_mask_signal(self.procs)
  File "D:\anaconda\lib\site-packages\tensorpack\utils\concurrency.py", line 244, in start_proc_mask_signal
    p.start()
  File "D:\anaconda\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\anaconda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
MemoryError

(base) D:\job\openposetf\unofficial-implement-of-openpose-master>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\anaconda\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

我的电脑配置是CPU i7-8550 内存 8GB GPU NVIDIA GeForce MX150
每次运行时CPU和内存占用率都90%以上

**Comment by jingshaoli** [comment]
我换了台内存16GB，1080Ti的电脑，结果出现了
