### ISSUE TITLE
使用coco数据集训练出错

### ISSUE THREAD

**Issue by jingshaoli** [YangZeyu95/unofficial-implement-of-openpose#31]
(base) C:\Users\ric\Desktop\PBL\ri\unofficial-implement-of-openpose-master\program>python train.py
[2019-05-31 09:54:12,264] [train] [INFO] Namespace(annot_path='C:/Users/ric/Desktop/PBL/ri/unofficial-implement-of-openpose-master/COCO/annotations/', backbone_net_ckpt_path='C:/Users/ric/Desktop/PBL/ri/unofficial-implement-of-openpose-master/checkpoints/vgg/vgg_19.ckpt', batch_size=10, checkpoint_path='C:/Users/ric/Desktop/PBL/ri/unofficial-implement-of-openpose-master/checkpoint/train', continue_training=False, hm_channels=19, img_path='C:/Users/ric/Desktop/PBL/ri/unofficial-implement-of-openpose-master/COCO/images/', input_height=368, input_width=368, loss_func='l2', max_echos=5, paf_channels=38, save_checkpoint_frequency=1000, save_summary_frequency=100, stage_num=6, train_vgg=True, use_bn=False)
[2019-05-31 09:54:12,265] [train] [INFO] checkpoint_path: C:/Users/ric/Desktop/PBL/ri/unofficial-implement-of-openpose-master/checkpoint/train2019-5-31-9-54-12
[2019-05-31 09:54:12,270] [train] [INFO] initializing data loader...
C:/Users/ric/Desktop/PBL/ri/unofficial-implement-of-openpose-master/COCO/annotations/
[2019-05-31 09:54:12,270] [pose_dataset] [INFO] dataflow img_path=C:/Users/ric/Desktop/PBL/ri/unofficial-implement-of-openpose-master/COCO/images/
loading annotations into memory...
Done (t=8.39s)
creating index...
index created!
[2019-05-31 09:54:20,857] [pose_dataset] [INFO] C:/Users/ric/Desktop/PBL/ri/unofficial-implement-of-openpose-master/COCO/annotations/ dataset 118287
[0531 09:54:20 @parallel.py:184] WRN MultiProcessPrefetchData does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
[0531 09:54:20 @parallel.py:194] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0531 09:56:27 @parallel.py:184] WRN MultiProcessPrefetchData does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
[0531 09:56:27 @parallel.py:194] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    train()
  File "train.py", line 79, in train
    df = get_dataflow_batch(args.annot_path, True, args.batch_size, img_path=args.img_path)
  File "C:\Users\ric\Desktop\PBL\ri\unofficial-implement-of-openpose-master\program\pose_dataset.py", line 390, in get_dataflow_batch
    ds = PrefetchData(ds, 10, 2)
  File "C:\Users\ric\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorpack\dataflow\parallel.py", line 201, in __init__
    start_proc_mask_signal(self.procs)
  File "C:\Users\ric\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorpack\utils\concurrency.py", line 244, in start_proc_mask_signal
    p.start()
  File "C:\Users\ric\AppData\Local\Continuum\anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\ric\AppData\Local\Continuum\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\ric\AppData\Local\Continuum\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\ric\AppData\Local\Continuum\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\ric\AppData\Local\Continuum\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle weakref objects

(base) C:\Users\ric\Desktop\PBL\ri\unofficial-implement-of-openpose-master\program>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ric\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\ric\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by YangZeyu95** [comment]
像是多线程的问题，建议使用ubuntu

**Comment by jingshaoli** [comment]
在aws上用ubuntu跑起来了，谢谢

**Comment by jingshaoli** [comment]
在aws上用ubuntu跑起来了，谢谢
