### ISSUE TITLE
博主 window环境下train 出现下面问题，怎么办呀？

### ISSUE THREAD

**Issue by Coderxiaobai1** [YangZeyu95/unofficial-implement-of-openpose#34]
(tensorflow-gpuversion) C:\Projects\unofficial-implement-of-openpose>python train_v2.py
[2019-07-04 00:12:14,387] [train] [INFO] Namespace(annot_path='COCO/annotations/', backbone_net_ckpt_path='checkpoints/vgg/vgg_19.ckpt', batch_size=10, checkpoint_path='checkpoints/train/', continue_training=False, hm_channels=19, img_path='COCO/images/', input_height=368, input_width=368, loss_func='l2', max_echos=5, paf_channels=38, save_checkpoint_frequency=1000, save_summary_frequency=100, stage_num=6, train_vgg=True, use_bn=False)
[2019-07-04 00:12:14,388] [train] [INFO] checkpoint_path: checkpoints/train/2019-7-4-0-12-14
[2019-07-04 00:12:14,391] [train] [INFO] initializing data loader...
[2019-07-04 00:12:14,391] [pose_dataset] [INFO] dataflow img_path=COCO/images/
loading annotations into memory...
Done (t=9.51s)
creating index...
index created!
[2019-07-04 00:12:24,121] [pose_dataset] [INFO] COCO/annotations/ dataset 118287
[0704 00:12:24 @parallel.py:184] WRN MultiProcessPrefetchData does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
[0704 00:12:24 @parallel.py:194] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
Failed to load OpenCL runtime
Failed to load OpenCL runtime
Failed to load OpenCL runtime
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\software\Anaconda3\envs\tensorflow-gpuversion\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\software\Anaconda3\envs\tensorflow-gpuversion\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
MemoryError
Traceback (most recent call last):
  File "train_v2.py", line 198, in <module>
    train()
  File "train_v2.py", line 80, in train
    df = get_dataflow_batch(args.annot_path, True, args.batch_size, img_path=args.img_path)
  File "C:\Projects\unofficial-implement-of-openpose\pose_dataset.py", line 389, in get_dataflow_batch
    ds = get_dataflow(path, is_train, img_path=img_path)
  File "C:\Projects\unofficial-implement-of-openpose\pose_dataset.py", line 368, in get_dataflow
    ds = PrefetchData(ds, 1000, multiprocessing.cpu_count()-1)
  File "C:\software\Anaconda3\envs\tensorflow-gpuversion\lib\site-packages\tensorpack\dataflow\parallel.py", line 201, in __init__
    start_proc_mask_signal(self.procs)
  File "C:\software\Anaconda3\envs\tensorflow-gpuversion\lib\site-packages\tensorpack\utils\concurrency.py", line 244, in start_proc_mask_signal
    p.start()
  File "C:\software\Anaconda3\envs\tensorflow-gpuversion\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\software\Anaconda3\envs\tensorflow-gpuversion\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\software\Anaconda3\envs\tensorflow-gpuversion\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\software\Anaconda3\envs\tensorflow-gpuversion\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\software\Anaconda3\envs\tensorflow-gpuversion\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by YangZeyu95** [comment]
多线程win上的确有问题，建议Ubuntu

**Comment by Coderxiaobai1** [comment]
谢谢您
