### ISSUE TITLE
problem with run

### ISSUE THREAD

**Issue by boyliwensheng** [YangZeyu95/unofficial-implement-of-openpose#39]
您好，感谢您做的工作，我现在跑``run.py``的过程中，在跑图片和视频的时候分别报了如下错误：不太懂这个函数是干什么的，所以不太好调试，麻烦帮忙看看，谢谢。
图片报错：
```
Traceback (most recent call last):
  File "E:/python_project/unofficial-implement-of-openpose-master/run.py", line 137, in <module>
    bodys = PoseEstimator.estimate_paf(peaks[0], heatmap[0], vectormap[0])
  File "E:\python_project\unofficial-implement-of-openpose-master\estimator.py", line 276, in estimate_paf
    pafprocess.process_paf(peaks, heat_mat, paf_mat)
NameError: name 'pafprocess' is not defined
```

视频报错：
```
Traceback (most recent call last):
  File "E:/python_project/unofficial-implement-of-openpose-master/run.py", line 114, in <module>
    bodys = PoseEstimator.estimate_paf(peaks[0], heatmap[0], vectormap[0])
  File "E:\python_project\unofficial-implement-of-openpose-master\estimator.py", line 276, in estimate_paf
    pafprocess.process_paf(peaks, heat_mat, paf_mat)
NameError: name 'pafprocess' is not defined
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 13 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
```

**Comment by YangZeyu95** [comment]
pafprocess需要自己编译一下，在pafprocess文件夹中有编译说明

**Comment by boyliwensheng** [comment]
请问编译是不是需要vs，不下载vs可以成功么

**Comment by YangZeyu95** [comment]
不需要，按照说明编译就行
