### ISSUE TITLE
请问一下这个可以在Windows下运行吗，为什么一运行就会出现cannot feed value of shape(10,184,184,19)for tensor 'inputs/Placeholder_1:0',which has shape '(10,46,46,19)'的错误，在train.py中将46改成184还是会出错

### ISSUE THREAD

**Issue by xiaolengtongxue** [YangZeyu95/unofficial-implement-of-openpose#5]

**Comment by YangZeyu95** [comment]
确保train.py中有这几行
![2018-12-27 4 05 09](https://user-images.githubusercontent.com/28431121/50471807-3ad02a80-09f1-11e9-9389-822240fd4645.png)
![2018-12-27 4 04 00](https://user-images.githubusercontent.com/28431121/50471812-3efc4800-09f1-11e9-90b4-9e9e0bbbc83c.png)

**Comment by YangZeyu95** [comment]
如果还不行调试一下pose_dataset.py的263和264行，他们的size应该是46*46

**Comment by xiaolengtongxue** [comment]
非常感谢您的回复，我下载的应该是您最新版本的代码，我已经把那两个路径都修改为本地路径，但是一开始训练就会报错，这是报错信息，您看看是不是我需要改一下代码还是少下了什么东西，非常感谢



------------------ 原始邮件 ------------------
发件人: "YangZeyu"<notifications@github.com>;
发送时间: 2018年12月27日(星期四) 下午4:05
收件人: "YangZeyu95/unofficial-implement-of-openpose"<unofficial-implement-of-openpose@noreply.github.com>;
抄送: "孤久則安"<384015098@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [YangZeyu95/unofficial-implement-of-openpose] 请问一下这个可以在Windows下运行吗，为什么一运行就会出现cannot feed value of shape(10,184,184,19)for tensor 'inputs/Placeholder_1:0',which has shape '(10,46,46,19)'的错误，在train.py中将46改成184还是会出错 (#5)




确保train.py中有这几行

**Comment by YangZeyu95** [comment]
可以直接在这里回复吗，我看不到报错信息

**Comment by xiaolengtongxue** [comment]
[2018-12-27 16:09:56,822] [train] [INFO] start training...
  0%|          | 0/11828 [00:00<?, ?it/s][2018-12-27 16:09:57,149] [pose_dataset] [ERROR] err type2, err=Cannot feed value of shape (10, 184, 184, 19) for Tensor 'inputs/Placeholder_1:0', which has shape '(10, 46, 46, 19)', placeholders=[<tf.Tensor 'inputs/Placeholder:0' shape=(10, 368, 368, 3) dtype=float32>, <tf.Tensor 'inputs/Placeholder_1:0' shape=(10, 46, 46, 19) dtype=float32>, <tf.Tensor 'inputs/Placeholder_2:0' shape=(10, 46, 46, 38) dtype=float32>]
[2018-12-27 16:09:57,149] [pose_dataset] [ERROR] Exception in Thread-1:Cannot feed value of shape (10, 184, 184, 19) for Tensor 'inputs/Placeholder_1:0', which has shape '(10, 46, 46, 19)'
Traceback (most recent call last):
  File "C:\Users\38401\Downloads\unofficial-implement-of-openpose-master\openpose\pose_dataset.py", line 442, in run
    self.op.run(feed_dict=feed)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\ops.py", line 2377, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\ops.py", line 5215, in _run_using_default_session
    session.run(operation, feed_dict)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1111, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (10, 184, 184, 19) for Tensor 'inputs/Placeholder_1:0', which has shape '(10, 46, 46, 19)'
[2018-12-27 16:10:01,632] [pose_dataset] [INFO] Thread-1 Exited.


Traceback (most recent call last):
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue)]]
	 [[Node: fifo_queue_Dequeue/_73 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_169_fifo_queue_Dequeue", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "C:/Users/38401/Downloads/unofficial-implement-of-openpose-master/openpose/train.py", line 196, in <module>
    train()
  File "C:/Users/38401/Downloads/unofficial-implement-of-openpose-master/openpose/train.py", line 162, in train
    total_loss, _, gs_num = sess.run([loss, train, global_step])
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue)]]
	 [[Node: fifo_queue_Dequeue/_73 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_169_fifo_queue_Dequeue", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


Caused by op 'fifo_queue_Dequeue', defined at:
  File "C:/Users/38401/Downloads/unofficial-implement-of-openpose-master/openpose/train.py", line 196, in <module>
    train()
  File "C:/Users/38401/Downloads/unofficial-implement-of-openpose-master/openpose/train.py", line 81, in train
    q_inp, q_heat, q_vect = enqueuer.dequeue()
  File "C:\Users\38401\Downloads\unofficial-implement-of-openpose-master\openpose\pose_dataset.py", line 464, in dequeue
    return self.queue.dequeue()
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 440, in dequeue
    self._queue_ref, self._dtypes, name=name)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 3733, in queue_dequeue_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "C:\Users\38401\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access


OutOfRangeError (see above for traceback): FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fifo_queue)]]
	 [[Node: fifo_queue_Dequeue/_73 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_169_fifo_queue_Dequeue", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]




Process finished with exit code 1

这是完整的报错信息，我只改了两个相对路径，您看看是我是不是有哪个地方需要改正一下，谢谢您了，非常感谢~




------------------ 原始邮件 ------------------
发件人: "YangZeyu"<notifications@github.com>;
发送时间: 2018年12月27日(星期四) 下午4:31
收件人: "YangZeyu95/unofficial-implement-of-openpose"<unofficial-implement-of-openpose@noreply.github.com>;
抄送: "孤久則安"<384015098@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [YangZeyu95/unofficial-implement-of-openpose] 请问一下这个可以在Windows下运行吗，为什么一运行就会出现cannot feed value of shape(10,184,184,19)for tensor 'inputs/Placeholder_1:0',which has shape '(10,46,46,19)'的错误，在train.py中将46改成184还是会出错 (#5)




可以直接在这里回复吗，我看不到报错信息

**Comment by YangZeyu95** [comment]
调试一下pose_dataset.py的263和264行，他们的size应该是46*46

**Comment by YangZeyu95** [comment]
或者直接把这两行里的scale换成8

**Comment by xiaolengtongxue** [comment]
好的，我明天去实验室改一下看看能不能运行，太感谢了，非常感谢~


------------------ 原始邮件 ------------------
发件人: "YangZeyu"<notifications@github.com>;
发送时间: 2018年12月27日(星期四) 晚上6:53
收件人: "YangZeyu95/unofficial-implement-of-openpose"<unofficial-implement-of-openpose@noreply.github.com>;
抄送: "孤久則安"<384015098@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [YangZeyu95/unofficial-implement-of-openpose] 请问一下这个可以在Windows下运行吗，为什么一运行就会出现cannot feed value of shape(10,184,184,19)for tensor 'inputs/Placeholder_1:0',which has shape '(10,46,46,19)'的错误，在train.py中将46改成184还是会出错 (#5)




或者直接把这两行里的scale换成8

**Comment by dishofchicken** [comment]
你好，请问解决了吗，我也遇到了同样的问题，谢谢：)

**Comment by AndyZCJ** [comment]
老哥，你解决了吗？我碰到和你一样的问题了

**Comment by YangZeyu95** [comment]
@AndyZCJ 
参考https://github.com/YangZeyu95/unofficial-implement-of-openpose/issues/12  已经可以解决了

**Comment by soveidadelgarmi** [comment]
Hi, I run train.py with coco dataset and I didn't have any problems. now I want to finetune it on my own dataset. but I receive this error...., I don't know what should I do exactly to solve it? can someone help me?

errore is:
[2019-07-14 07:50:50,943] [train] [INFO] start training...
I0714 07:50:50.943787 140334568265600 :181] start training...
0%| | 0/21 [00:00<?, ?it/s][2019-07-14 07:50:51,013] [pose_dataset] [ERROR] err type2, err=Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)', placeholders=[<tf.Tensor 'inputs/Placeholder:0' shape=(5, 368, 368, 3) dtype=float32>, <tf.Tensor 'inputs/Placeholder_1:0' shape=(5, 46, 46, 11) dtype=float32>, <tf.Tensor 'inputs/Placeholder_2:0' shape=(5, 46, 46, 22) dtype=float32>]
E0714 07:50:51.013219 140329005074176 pose_dataset.py:485] err type2, err=Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)', placeholders=[<tf.Tensor 'inputs/Placeholder:0' shape=(5, 368, 368, 3) dtype=float32>, <tf.Tensor 'inputs/Placeholder_1:0' shape=(5, 46, 46, 11) dtype=float32>, <tf.Tensor 'inputs/Placeholder_2:0' shape=(5, 46, 46, 22) dtype=float32>]
[2019-07-14 07:50:51,015] [pose_dataset] [ERROR] Exception in Thread-5:Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)'
Traceback (most recent call last):
File "/content/drive/My Drive/Mythesiscode/pose_dataset.py", line 479, in run
self.op.run(feed_dict=feed)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2679, in run
_run_using_default_session(self, feed_dict, self.graph, session)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 5614, in _run_using_default_session
session.run(operation, feed_dict)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
run_metadata_ptr)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1149, in _run
str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)'
E0714 07:50:51.015784 140329005074176 pose_dataset.py:489] Exception in Thread-5:Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)'
Traceback (most recent call last):
File "/content/drive/My Drive/Mythesiscode/pose_dataset.py", line 479, in run
self.op.run(feed_dict=feed)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2679, in run
_run_using_default_session(self, feed_dict, self.graph, session)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 5614, in _run_using_default_session
session.run(operation, feed_dict)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
run_metadata_ptr)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1149, in _run
str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (5, 46, 46, 11) for Tensor 'inputs/Placeholder:0', which has shape '(5, 368, 368, 3)'

OutOfRangeError: 2 root error(s) found.
(0) Out of range: FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
[[node fifo_queue_Dequeue (defined at /content/drive/My Drive/Mythesiscode/pose_dataset.py:501) ]]
(1) Out of range: FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
[[node fifo_queue_Dequeue (defined at /content/drive/My Drive/Mythesiscode/pose_dataset.py:501) ]]
[[fifo_queue_Dequeue/_75]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node fifo_queue_Dequeue:
fifo_queue (defined at /content/drive/My Drive/Mythesiscode/pose_dataset.py:440)

Input Source operations connected to node fifo_queue_Dequeue:
fifo_queue (defined at /content/drive/My Drive/Mythesiscode/pose_dataset.py:440)

Original stack trace for 'fifo_queue_Dequeue':
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py", line 16, in 
app.launch_new_instance()
File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 658, in launch_instance
app.start()
File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py", line 477, in start
ioloop.IOLoop.instance().start()
File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 888, in start
handler_func(fd_obj, events)
File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
self._handle_recv()
File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
self._run_callback(callback, msg)
File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
callback(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
handler(stream, idents, msg)
File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
user_expressions, allow_stdin)
File "/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
res = shell.run_cell(code, store_history=store_history, silent=silent)
File "/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
interactivity=interactivity, compiler=compiler, result=result)
File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
if self.run_code(code, result):
File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "", line 2, in 
train()
File "", line 78, in train
q_inp, q_heat, q_vect = enqueuer.dequeue()
File "/content/drive/My Drive/Mythesiscode/pose_dataset.py", line 501, in dequeue
return self.queue.dequeue()
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 445, in dequeue
self._queue_ref, self._dtypes, name=name)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4140, in queue_dequeue_v2
timeout_ms=timeout_ms, name=name)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
op_def=op_def)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
return func(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
op_def=op_def)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2005, in init
self._traceback = tf_stack.extract_stack()

**Comment by walkm-an** [comment]
> _No description provided._

老哥，你Windows怎么make pafprocess， win上面swig怎么用哇？
谢谢
