### ISSUE TITLE
Windows上的训练问题

### ISSUE THREAD

**Issue by 7StarX** [YangZeyu95/unofficial-implement-of-openpose#69]
你好，我在Windows上训练模型，但是遇到了这个情况：
'can only start a process object created by current process'
他就提示这个，然后一直不动，GPU和CPU都不动。应该怎么解决呢？望回复，非常感谢！！

**Comment by 7StarX** [comment]
我的tensorflow版本是gpu版本的1.15.0

**Comment by YangZeyu95** [comment]
More log?

**Comment by cfsfine** [comment]
我也是遇到了这个问题，就是'can only start a process object created by current process'！

**Comment by zhanghaobucunzai** [comment]
我也遇到了  请问怎么解决？ 对python版本有要求吗

**Comment by zhanghaobucunzai** [comment]
> 你好，我在的Windows上训练模型，但是遇到了这个情况：
> '只能通过启动当前进程创建的进程对象'
> 他就提示这个，然后一直不动，GPU和CPU都不动应该怎么解决呢？望回复，非常感谢！！

请问这个问题解决了吗？ 是怎么解决的

**Comment by zhanghaobucunzai** [comment]
> 我也是遇到了这个问题，就是“只能启动当前流程创建的流程对象”！

请问这个问题解决了吗？是怎么解决的

**Comment by YangZeyu95** [comment]
Windows上的多线程问题，可以关了多线程，但是会很慢
建议换Ubuntu

**Comment by zhanghaobucunzai** [comment]
> Windows上的多线程问题，可以关了多线程，但是会很慢
> 建议换Ubuntu

我是在GPU环境  不是windows

**Comment by YangZeyu95** [comment]
> > Windows上的多线程问题，可以关了多线程，但是会很慢
> > 建议换Ubuntu
> 
> 我是在GPU环境 不是windows

GPU环境指的是？

**Comment by zhanghaobucunzai** [comment]
> > > Windows上的多线程问题，可以关了多线程，但是会很慢
> > > 建议换Ubuntu
> > 
> > 
> > 我是在GPU环境不是windows
> 
> GPU环境指的是？
我把报错贴进来帮忙看下   我是在donker内执行的，里面就是ubuntu的

**Comment by zhanghaobucunzai** [comment]
> > > Windows上的多线程问题，可以关了多线程，但是会很慢
> > > 建议换Ubuntu
> > 
> > 
> > 我是在GPU环境不是windows
> 
> GPU环境指的是？

[0519 16:30:31 @parallel.py:219] [MultiProcessRunner] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
WARNING:tensorflow:From /user/swx689421/openpose/pose_dataset.py:406: The name tf.FIFOQueue is deprecated. Please use tf.queue.FIFOQueue instead.

[2016-05-19 16:30:31,480] [pose_dataset] [INFO] dataflow img_path=./dataset/COCO/images/
loading annotations into memory...
Done (t=0.30s)
creating index...
index created!
[2016-05-19 16:30:31,791] [pose_dataset] [INFO] ./dataset/COCO/annotations/ dataset 5000
[0519 16:30:31 @parallel.py:219] [MultiProcessRunner] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0519 16:30:31 @parallel.py:219] [MultiProcessRunner] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0519 16:30:31 @argtools.py:138] WRN Starting a process with 'fork' method is efficient but not safe and may cause deadlock or crash.Use 'forkserver' or 'spawn' method instead if you run into such issues.See https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods on how to set them.
Process _Worker-92:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/parallel.py", line 190, in run
    self.ds.reset_state()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/base.py", line 181, in reset_state
    self.ds.reset_state()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/parallel.py", line 238, in reset_state
    start_proc_mask_signal(self.procs)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/utils/concurrency.py", line 240, in start_proc_mask_signal
    p.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 101, in start
    'can only start a process object created by current process'
AssertionError: can only start a process object created by current process
[2016-05-19 16:30:31,834] [train] [INFO] initializing model...
WARNING:tensorflow:From /user/swx689421/openpose/vgg.py:244: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

Process _Worker-93:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/parallel.py", line 190, in run
    self.ds.reset_state()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/base.py", line 181, in reset_state
    self.ds.reset_state()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/parallel.py", line 238, in reset_state
    start_proc_mask_signal(self.procs)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/utils/concurrency.py", line 240, in start_proc_mask_signal
    p.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 101, in start
    'can only start a process object created by current process'
AssertionError: can only start a process object created by current process
WARNING:tensorflow:From /user/swx689421/openpose/cpm.py:141: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /user/swx689421/openpose/cpm.py:153: The name tf.summary.histogram is deprecated. Please use tf.compat.v1.summary.histogram instead.

[2016-05-19 16:30:34,215] [train] [INFO] use l2 loss
[2016-05-19 16:30:34,220] [train] [INFO] use l2 loss
[2016-05-19 16:30:34,224] [train] [INFO] use l2 loss
[2016-05-19 16:30:34,229] [train] [INFO] use l2 loss
[2016-05-19 16:30:34,233] [train] [INFO] use l2 loss
[2016-05-19 16:30:34,238] [train] [INFO] use l2 loss
WARNING:tensorflow:From train.py:116: The name tf.train.exponential_decay is deprecated. Please use tf.compat.v1.train.exponential_decay instead.

WARNING:tensorflow:From train.py:117: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From train.py:117: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From train.py:121: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

[2016-05-19 16:30:36,035] [train] [INFO] initialize saver...
WARNING:tensorflow:From train.py:125: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

[2016-05-19 16:30:36,166] [train] [INFO] initialize tensorboard
WARNING:tensorflow:From train.py:129: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From train.py:134: The name tf.summary.image is deprecated. Please use tf.compat.v1.summary.image instead.

[2016-05-19 16:30:36,212] [train] [INFO] initialize session...
WARNING:tensorflow:From train.py:144: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

WARNING:tensorflow:From train.py:145: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From train.py:147: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2016-05-19 16:30:36.646997: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000130000 Hz
2016-05-19 16:30:37.061554: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5b05180 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2016-05-19 16:30:37.061609: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2016-05-19 16:30:37.072602: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2016-05-19 16:30:37.470142: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5a3ad20 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2016-05-19 16:30:37.470190: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-SXM2-32GB, Compute Capability 7.0
2016-05-19 16:30:37.474082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 0 with properties:
name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:b5:00.0
2016-05-19 16:30:37.474134: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2016-05-19 16:30:37.490696: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2016-05-19 16:30:37.491883: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2016-05-19 16:30:37.492163: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2016-05-19 16:30:37.495022: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2016-05-19 16:30:37.495672: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2016-05-19 16:30:37.495809: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2016-05-19 16:30:37.498740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1762] Adding visible gpu devices: 0
2016-05-19 16:30:37.498770: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2016-05-19 16:30:37.975980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1175] Device interconnect StreamExecutor with strength 1 edge matrix:
2016-05-19 16:30:37.976017: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181]      0
2016-05-19 16:30:37.976025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 0:   N
2016-05-19 16:30:37.979578: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30168 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:b5:00.0, compute capability: 7.0)
WARNING:tensorflow:From train.py:148: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

WARNING:tensorflow:From train.py:149: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

[2016-05-19 16:30:42,812] [train] [INFO] restoring vgg weights from checkpoints/vgg/vgg_19.ckpt
[2016-05-19 16:30:53,178] [train] [INFO] start training...
WARNING:tensorflow:From /user/swx689421/openpose/pose_dataset.py:428: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

  0%|                                                                                                                                                                                | 0/11828 [00:00<?, ?it/s]Process _Worker-72:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/parallel.py", line 190, in run
    self.ds.reset_state()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/base.py", line 181, in reset_state
    self.ds.reset_state()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/parallel.py", line 238, in reset_state
    start_proc_mask_signal(self.procs)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/utils/concurrency.py", line 240, in start_proc_mask_signal
    p.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 101, in start
    'can only start a process object created by current process'
AssertionError: can only start a process object created by current process
Process _Worker-73:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/parallel.py", line 190, in run
    self.ds.reset_state()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/base.py", line 181, in reset_state
    self.ds.reset_state()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/parallel.py", line 238, in reset_state
    start_proc_mask_signal(self.procs)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/utils/concurrency.py", line 240, in start_proc_mask_signal
    p.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 101, in start
    'can only start a process object created by current process'
AssertionError: can only start a process object created by current process

**Comment by zhanghaobucunzai** [comment]
> > > Windows上的多线程问题，可以关了多线程，但是会很慢
> > > 建议换Ubuntu
> > 
> > 
> > 我是在GPU环境 不是windows
> 
> GPU环境指的是？

帮瞅瞅

**Comment by YangZeyu95** [comment]
看起来是跟Windows同样的问题，

**Comment by zhanghaobucunzai** [comment]
> 看起来是跟Windows同样的问题，

代码里面能优化解决吗

**Comment by zhanghaobucunzai** [comment]
> 看起来是跟Windows同样的问题，

此乃linux环境

**Comment by zhanghaobucunzai** [comment]
> 看起来是跟Windows同样的问题，

linux怎么关多线程啊

**Comment by YangZeyu95** [comment]
> > 看起来是跟Windows同样的问题，
> 
> linux怎么关多线程啊

pose_dataset.py: line 367
cpu_cont那个参数改成1

**Comment by zhanghaobucunzai** [comment]
> pu_cont那个参数改成1

 # ds = PrefetchData(ds, 1000, multiprocessing.cpu_count()-1)
        ds = PrefetchData(ds, 1000, 1)
        print("1111111111111111111111111111")
    else:
        ds = MultiThreadMapData(ds, num_thread=16, map_func=read_image_url, buffer_size=1000)
        ds = MapDataComponent(ds, pose_resize_shortestedge_fixed)
        ds = MapDataComponent(ds, pose_crop_center)
        ds = MapData(ds, pose_to_img)
        #ds = PrefetchData(ds, 100, multiprocessing.cpu_count() // 4)
        ds = PrefetchData(ds, 100, 1)
        print("22222222222222222222222222222")

我改成了1，还是不行，会卡住

**Comment by zhanghaobucunzai** [comment]
> > > 看起来是跟Windows同样的问题，
> > 
> > 
> > linux怎么关多线程啊
> 
> pose_dataset.py: line 367
> cpu_cont那个参数改成1

大佬在不，帮解决下这个问题
