### ISSUE TITLE
Linux ten 4.15.0-140-generic #144~16.04.1-Ubuntu SMP Fri Mar 19 21:24:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### ISSUE THREAD

**Issue by CARASO** [YangZeyu95/unofficial-implement-of-openpose#76]
python -u ~/openpose/train.py --annot_path ~/dataset/myCoCo/annotations --img_path ~/dataset/myCoCo/images
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

OpenCV is built with OpenMP support. This usually results in poor performance. For details, see https://github.com/tensorpack/benchmarks/blob/master/ImageNet/benchmark-opencv-resize.py
[2021-04-26 20:35:24,766] [train] [INFO] Namespace(annot_path='~/dataset/myCoCo/annotations', backbone_net_ckpt_path='checkpoints/vgg/vgg_19.ckpt', batch_size=10, checkpoint_path='checkpoints/train/', continue_training=False, hm_channels=19, img_path='~/dataset/myCoCo/images', input_height=368, input_width=368, loss_func='l2', max_echos=5, paf_channels=38, save_checkpoint_frequency=1000, save_summary_frequency=100, stage_num=6, train_vgg=True, use_bn=False)
[2021-04-26 20:35:24,766] [train] [INFO] checkpoint_path: checkpoints/train/2021-4-26-20-35-24
WARNING:tensorflow:From ~/openpose/train.py:69: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

[2021-04-26 20:35:24,772] [train] [INFO] initializing data loader...
[2021-04-26 20:35:24,773] [pose_dataset] [INFO] dataflow img_path=~/dataset/myCoCo/images
loading annotations into memory...
Done (t=3.07s)
creating index...
index created!
[2021-04-26 20:35:28,425] [pose_dataset] [INFO] ~/dataset/myCoCo/annotations dataset 188161
[0426 20:35:28 @parallel.py:219] [MultiProcessRunner] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0426 20:35:28 @parallel.py:219] [MultiProcessRunner] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
WARNING:tensorflow:From ~/openpose/pose_dataset.py:405: The name tf.FIFOQueue is deprecated. Please use tf.queue.FIFOQueue instead.

[2021-04-26 20:35:28,458] [train] [INFO] initializing model...
WARNING:tensorflow:From ~/openpose/vgg.py:244: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From ~/openpose/cpm.py:141: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From ~/openpose/cpm.py:153: The name tf.summary.histogram is deprecated. Please use tf.compat.v1.summary.histogram instead.

[2021-04-26 20:35:31,215] [train] [INFO] use l2 loss
[2021-04-26 20:35:31,222] [train] [INFO] use l2 loss
[2021-04-26 20:35:31,229] [train] [INFO] use l2 loss
[2021-04-26 20:35:31,236] [train] [INFO] use l2 loss
[2021-04-26 20:35:31,243] [train] [INFO] use l2 loss
[2021-04-26 20:35:31,250] [train] [INFO] use l2 loss
WARNING:tensorflow:From ~/openpose/train.py:117: The name tf.train.exponential_decay is deprecated. Please use tf.compat.v1.train.exponential_decay instead.

WARNING:tensorflow:From ~/openpose/train.py:118: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From ~/openpose/train.py:118: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From ~/openpose/train.py:122: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

[2021-04-26 20:35:35,383] [train] [INFO] initialize saver...
WARNING:tensorflow:From ~/openpose/train.py:126: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

[2021-04-26 20:35:35,637] [train] [INFO] initialize tensorboard
WARNING:tensorflow:From ~/openpose/train.py:130: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From ~/openpose/train.py:135: The name tf.summary.image is deprecated. Please use tf.compat.v1.summary.image instead.

[2021-04-26 20:35:35,715] [train] [INFO] initialize session...
WARNING:tensorflow:From ~/openpose/train.py:145: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

WARNING:tensorflow:From ~/openpose/train.py:146: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From ~/openpose/train.py:148: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2021-04-26 20:35:35.733580: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2021-04-26 20:35:35.796811: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2000089999 Hz
2021-04-26 20:35:35.817686: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555ad2c1b160 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-26 20:35:35.817767: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-04-26 20:35:35.819597: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-26 20:35:39.266956: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 0 and 9, status: Internal: failed to enable peer access from 0x555ad3237be0 to 0x555ad618dae0: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.286430: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 1 and 9, status: Internal: failed to enable peer access from 0x555ad37f4860 to 0x555ad618dae0: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.300603: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 2 and 9, status: Internal: failed to enable peer access from 0x555ad3d09dd0 to 0x555ad618dae0: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.317039: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 3 and 9, status: Internal: failed to enable peer access from 0x555ad42273e0 to 0x555ad618dae0: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.327871: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 4 and 9, status: Internal: failed to enable peer access from 0x555ad474dab0 to 0x555ad618dae0: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.334489: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 5 and 9, status: Internal: failed to enable peer access from 0x555ad4c7bbc0 to 0x555ad618dae0: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.334952: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 6 and 8, status: Internal: failed to enable peer access from 0x555ad51b2210 to 0x555ad5c39420: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.335598: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 7 and 9, status: Internal: failed to enable peer access from 0x555ad56f0e60 to 0x555ad618dae0: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.335809: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 8 and 6, status: Internal: failed to enable peer access from 0x555ad5c39420 to 0x555ad51b2210: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.336166: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 9 and 0, status: Internal: failed to enable peer access from 0x555ad618dae0 to 0x555ad3237be0: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.336402: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 9 and 1, status: Internal: failed to enable peer access from 0x555ad618dae0 to 0x555ad37f4860: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.336600: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 9 and 2, status: Internal: failed to enable peer access from 0x555ad618dae0 to 0x555ad3d09dd0: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.336794: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 9 and 3, status: Internal: failed to enable peer access from 0x555ad618dae0 to 0x555ad42273e0: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.336969: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 9 and 4, status: Internal: failed to enable peer access from 0x555ad618dae0 to 0x555ad474dab0: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.337143: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 9 and 5, status: Internal: failed to enable peer access from 0x555ad618dae0 to 0x555ad4c7bbc0: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.337334: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1575] Unable to enable peer access between device ordinals 9 and 7, status: Internal: failed to enable peer access from 0x555ad618dae0 to 0x555ad56f0e60: CUDA_ERROR_TOO_MANY_PEERS: peer mapping resources exhausted
2021-04-26 20:35:39.339249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:04:00.0
2021-04-26 20:35:39.341013: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:05:00.0
2021-04-26 20:35:39.345904: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:06:00.0
2021-04-26 20:35:39.349367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:07:00.0
2021-04-26 20:35:39.350831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 4 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:08:00.0
2021-04-26 20:35:39.352520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 5 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0b:00.0
2021-04-26 20:35:39.353927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 6 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0c:00.0
2021-04-26 20:35:39.355364: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 7 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0d:00.0
2021-04-26 20:35:39.356894: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 8 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0e:00.0
2021-04-26 20:35:39.358291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 9 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0f:00.0
2021-04-26 20:35:39.358764: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-04-26 20:35:39.360955: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-04-26 20:35:39.362900: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2021-04-26 20:35:39.363384: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2021-04-26 20:35:39.365212: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2021-04-26 20:35:39.366981: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2021-04-26 20:35:39.373681: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-04-26 20:35:39.418037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
2021-04-26 20:35:39.418202: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-04-26 20:35:39.440917: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-26 20:35:39.440990: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 2 3 4 5 6 7 8 9 
2021-04-26 20:35:39.441014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N Y Y Y Y Y Y Y Y Y 
2021-04-26 20:35:39.441029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   Y N Y Y Y Y Y Y Y Y 
2021-04-26 20:35:39.441039: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 2:   Y Y N Y Y Y Y Y Y Y 
2021-04-26 20:35:39.441053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 3:   Y Y Y N Y Y Y Y Y Y 
2021-04-26 20:35:39.441064: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 4:   Y Y Y Y N Y Y Y Y Y 
2021-04-26 20:35:39.441076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 5:   Y Y Y Y Y N Y Y Y Y 
2021-04-26 20:35:39.441087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 6:   Y Y Y Y Y Y N Y Y Y 
2021-04-26 20:35:39.441098: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 7:   Y Y Y Y Y Y Y N Y Y 
2021-04-26 20:35:39.441110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 8:   Y Y Y Y Y Y Y Y N Y 
2021-04-26 20:35:39.441121: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 9:   Y Y Y Y Y Y Y Y Y N 
2021-04-26 20:35:39.467067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3134 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
2021-04-26 20:35:39.471514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 2110 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1)
2021-04-26 20:35:39.477056: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 2110 MB memory) -> physical GPU (device: 2, name: GeForce GTX 1080 Ti, pci bus id: 0000:06:00.0, compute capability: 6.1)
2021-04-26 20:35:39.480789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 2110 MB memory) -> physical GPU (device: 3, name: GeForce GTX 1080 Ti, pci bus id: 0000:07:00.0, compute capability: 6.1)
2021-04-26 20:35:39.487006: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 2110 MB memory) -> physical GPU (device: 4, name: GeForce GTX 1080 Ti, pci bus id: 0000:08:00.0, compute capability: 6.1)
2021-04-26 20:35:39.492636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:5 with 10489 MB memory) -> physical GPU (device: 5, name: GeForce GTX 1080 Ti, pci bus id: 0000:0b:00.0, compute capability: 6.1)
2021-04-26 20:35:39.499115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:6 with 681 MB memory) -> physical GPU (device: 6, name: GeForce GTX 1080 Ti, pci bus id: 0000:0c:00.0, compute capability: 6.1)
2021-04-26 20:35:39.507638: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:7 with 3038 MB memory) -> physical GPU (device: 7, name: GeForce GTX 1080 Ti, pci bus id: 0000:0d:00.0, compute capability: 6.1)
2021-04-26 20:35:39.516113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:8 with 2552 MB memory) -> physical GPU (device: 8, name: GeForce GTX 1080 Ti, pci bus id: 0000:0e:00.0, compute capability: 6.1)
2021-04-26 20:35:39.524909: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:9 with 1799 MB memory) -> physical GPU (device: 9, name: GeForce GTX 1080 Ti, pci bus id: 0000:0f:00.0, compute capability: 6.1)
2021-04-26 20:35:39.531475: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555ad66d3130 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-04-26 20:35:39.531547: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-04-26 20:35:39.531559: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-04-26 20:35:39.531569: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (2): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-04-26 20:35:39.531578: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (3): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-04-26 20:35:39.531587: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (4): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-04-26 20:35:39.531596: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (5): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-04-26 20:35:39.531605: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (6): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-04-26 20:35:39.531614: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (7): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-04-26 20:35:39.531623: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (8): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-04-26 20:35:39.531631: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (9): GeForce GTX 1080 Ti, Compute Capability 6.1
WARNING:tensorflow:From ~/openpose/train.py:149: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

WARNING:tensorflow:From ~/openpose/train.py:150: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

[2021-04-26 20:35:46,002] [train] [INFO] restoring vgg weights from checkpoints/vgg/vgg_19.ckpt
[2021-04-26 20:35:49,519] [train] [INFO] start training...
WARNING:tensorflow:From ~/openpose/pose_dataset.py:427: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

[0426 20:35:49 @argtools.py:138] WRN Starting a process with 'fork' method is efficient but not safe and may cause deadlock or crash.Use 'forkserver' or 'spawn' method instead if you run into such issues.See https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods on how to set them.
  0%|                                                 | 0/18816 [00:00<?, ?it/s]Process _Worker-56:
Traceback (most recent call last):
  File "~/anaconda3/envs/py37/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "~/anaconda3/envs/py37/lib/python3.7/site-packages/tensorpack/dataflow/parallel.py", line 190, in run
    self.ds.reset_state()
  File "~/anaconda3/envs/py37/lib/python3.7/site-packages/tensorpack/dataflow/base.py", line 181, in reset_state
    self.ds.reset_state()
  File "~/anaconda3/envs/py37/lib/python3.7/site-packages/tensorpack/dataflow/parallel.py", line 238, in reset_state
    start_proc_mask_signal(self.procs)
  File "~/anaconda3/envs/py37/lib/python3.7/site-packages/tensorpack/utils/concurrency.py", line 240, in start_proc_mask_signal
    p.start()
  File "~/anaconda3/envs/py37/lib/python3.7/multiprocessing/process.py", line 108, in start
    'can only start a process object created by current process'
AssertionError: can only start a process object created by current process
Process _Worker-57:
Traceback (most recent call last):
  File "~/anaconda3/envs/py37/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "~/anaconda3/envs/py37/lib/python3.7/site-packages/tensorpack/dataflow/parallel.py", line 190, in run
    self.ds.reset_state()
  File "~/anaconda3/envs/py37/lib/python3.7/site-packages/tensorpack/dataflow/base.py", line 181, in reset_state
    self.ds.reset_state()
  File "~/anaconda3/envs/py37/lib/python3.7/site-packages/tensorpack/dataflow/parallel.py", line 238, in reset_state
    start_proc_mask_signal(self.procs)
  File "~/anaconda3/envs/py37/lib/python3.7/site-packages/tensorpack/utils/concurrency.py", line 240, in start_proc_mask_signal
    p.start()
  File "~/anaconda3/envs/py37/lib/python3.7/multiprocessing/process.py", line 108, in start
    'can only start a process object created by current process'
AssertionError: can only start a process object created by current process

**Comment by KP1-cmd** [comment]
@CARASO  hello, did you get solution for this issue? i am getting the same error
Thank you !

**Comment by CARASO** [comment]
> @CARASO hello, did you get solution for this issue? i am getting the same error
> Thank you !

I reinstalled "tensorpack" and it work , you can try it.

**Comment by CARASO** [comment]
> @CARASO hello, did you get solution for this issue? i am getting the same error
> Thank you !

@KP1-cmd I have reinstalled the "tensorpack".

**Comment by bilalkhann16** [comment]
Hello, I'm getting the same error. I tried to reinstall the tensorpack on M1 but still no luck. Could you please tell me what tensorpack version you installed? Thanks.
